package:
  name: astra-toolbox
  version: '2.1.2'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_tag: master

build:
  number: 0

test:
  imports:
    - astra
  requires:
    # To avoid large downloads just for testing after build phase
    - nomkl # [not win]
    # import scipy.sparse.linalg fails with mkl-2017.0.4 on Windows
    - mkl !=2017.0.4 # [win]
    # scipy 1.1.0 packages are broken with python 2.7 and some numpy versions
    - scipy !=1.1.0 # [py27]

requirements:
  build:
    - {{ compiler('c') }}    # [win or linux]
    - {{ compiler('cxx') }}  # [linux]
  host:
    - python
    - cython >=0.13
    - boost # [osx or linux]
    - nomkl # [not win]
    - numpy {{ numpy }}
    - scipy
    - six
    - libastra ==2.1.2
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - scipy
    - six
    # We make this libastra requirement as strict as possible because we
    # want to enforce matching astra-toolbox and libastra packages to limit
    # chances of API/ABI incompatibility.
    # The 'cuda_*' build string is designed to match our packages but not
    # current conda-forge/libastra packages which use a different format.
    - libastra ==2.1.2 cuda_* # [win or linux]
    - libastra ==2.1.2 nocuda_* # [osx]


about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
