package:
  name: astra-toolbox
  version: '1.8b'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_rev: master  # for testing
  # git_tag: 1.8  # TODO: change to this for next release

build:
  number: 0
  script_env:
    - CC
    - CUDA_ROOT

test:
  imports:
    - astra

  requires:
    # To avoid large downloads just for testing after build phase
    - nomkl # [not win]

requirements:
  build:
    - python
    - cython >=0.13
    - nomkl # [not win]
    - numpy
    - scipy
    - six
    - libastra ==1.8b  # TODO: change to release version

  run:
    - python
    - numpy
    - scipy
    - six
    - libastra ==1.8b  # TODO: change to release version


about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
