package:
  name: libastra
  version: '1.8b'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_rev: master  # for testing
  # git_tag: 1.8  # TODO: change to this for next release

build:
  number: 0
  script_env:
    - CC
    - CXX
    - CUDA_ROOT

requirements:
  build:
    - boost

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
