package:
  name: libastra
  version: '1.8'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_tag: v1.8

build:
  number: 0
  script_env:
    - CC # [not win]
    - CXX # [not win]
    - CUDA_ROOT # [not win]

requirements:
  build:
    - vs2015_runtime # [win]
    - boost # [osx]
    - automake # [osx]
    - autoconf # [osx]
    - libtool # [osx]

  run:
    - vs2015_runtime # [win]

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
